version: '3'
services:
  app:
    image: golang:1.21.4
    container_name: ukrzaliznytsia
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "go mod download && cd cmd/ && go run ."
